# Generated by Django 5.2.8 on 2025-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], max_length=10)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id_dueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'duenos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialVacunacion',
            fields=[
                ('id_vacunacion', models.AutoField(primary_key=True, serialize=False)),
                ('dosis_numero', models.SmallIntegerField()),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_proxima', models.DateField()),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'historial_vacunacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dosis_requeridas', models.SmallIntegerField()),
                ('intervalo_dias', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'vacunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'veterinarios',
                'managed': False,
            },
        ),
    ]
